### ISSUE TITLE
subscription.url in .graphqlconfig is ignored on 'Execute Subscription'

### ISSUE THREAD

**Issue by shiatsumat** [prisma/vscode-graphql#127]
When I click 'Execute Subscription' in *.graphql files,
the `subscription.url` property (e.g. `ws://localhost:3000/grapql`) of the endpoint in `.graphqlconfig.yml` is ignored, and instead the `url` property (e.g. `http://localhost:3000/graphql`) of the endpoint (automatically replacing `http://` with `ws://`, probably) is referred to.

The output of the GraphQL Language Service is as follows.
```
NetworkHelper: operation: subscription
NetworkHelper: endpoint: http://localhost:5000/graphql
```
`.graphqlconfig.yml` looks like this.
```
projects:
  app:
    schemaPath: ...
    includes: [...]
    extensions:
      endpoints:
        dev:
          url: http://localhost:3000/graphql
          subscription:
            url: ws://localhost:3000/graphql

```
The environment is as follows.
- GraphQL for VSCode Extension: version 0.2.1
- VSCode: version 1.37.1
- OS: Ubuntu 19.04
